trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: npm install
  displayName: Install dependencies

- script: npx playwright install --with-deps
  displayName: Install browsers

- script: npx playwright test
  displayName: Run tests

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'playwright-report'
    artifactName: 'PlaywrightReport'